package mockup.sql;

import mockup.Replaces;
import ourlib.nonapp.TaintAPI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

@Replaces("java.sql.Statement")
public abstract class DummyStatement implements Statement {

    public boolean execute(String sql) throws SQLException {
        TaintAPI.outputString(sql);
        return true;
    }

    public int executeUpdate(String sql) throws SQLException {
        TaintAPI.outputString(sql);
        return 1;
    }

    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        TaintAPI.outputString(sql);
        return 1;
    }

    public int executeUpdate(String sql, int columnIndexes[]) throws SQLException {
        TaintAPI.outputString(sql);
        return 1;
    }

    public int executeUpdate(String sql, String columnNames[]) throws SQLException {
        TaintAPI.outputString(sql);
        for (String s : columnNames) {
            TaintAPI.outputString(s);
        }
        return 1;
    }

    public ResultSet executeQuery(String sql) throws SQLException {
        TaintAPI.outputString(sql);
        return null;
    }
}
